### ISSUE TITLE
Most Ranged Enchantments Does Not Function with Crossbows

### ISSUE THREAD

**Issue by EigentlicherVogel** [chronosacaria/MCDungeonsWeapons#103]
- Versions:

Minecraft 1.18.2
Fabric 0.13.3
MCDW 4.2.5

- Other mods:

Mmm...mM(Training Dummy Mod) 1.5.1
Sodium 0.4.1+build15

- Description:

A sizable part of ranged enchantments, despite being enchantable to crossbows via normal enchantment and some innate to certain crossbows, does not function on crossbows despite working on bows normally. 

>Enchantments that does function on bows but does not on crossbows: Chain Reaction, Gravity, Fuse Shot, Radiance, Bonus Shot, Ricochet, Cobweb Shot, Levitation Shot, Poison Cloud
>Enchantments that does function on both bows and crossbows: Growing, Void Shot, Enigma Resonator

 - Reproduction:

0. (optional) Use config to change the trigger chance of Chain Reaction to 100%
1. Obtain a Firebolt Thrower
2. Fire at any entity (single or multiple times)
3. No extra arrows are fired.

**Comment by Kluzzio** [comment]
In my testing with our dev environment I quickly discovered that chain reaction DOES indeed work on crossbows. Though quite hilariously, it does not seem to be at all close to what the enchantment is intended to do.
I will continue testing but just wanted to share that, if you look closely, additional arrows do indeed spawn (albeit at mach 5 in the perpendicular directions).

**Comment by Kluzzio** [comment]
Gravity works as intended with crossbows. It pulls nearby mobs toward the hit target.
Likewise the following worked in my testing:
Fuse Shot, Radiance, Ricochet, Cobweb Shot, Levitation Shot, Poison Cloud

These work but need revisiting bc they are janky:
~~Chain Reaction, Bonus Shot~~ (Edit: Not Janky. Just am dumb. They work as intended)

These tests were only done with crossbows, not bows. Something to keep in mind is that your tests were likely accurate as well because there are some differences in the code, but this is what I found in my tests. That being said, thank you for both of your issue reports!

**Comment by EigentlicherVogel** [comment]
Are these changes on Github yet?

Edit: Downloaded and compiled mod from source. Crossbow enchantments does indeed work. Maybe a new version push to curseforge is warranted? Either way closing the issue I guess. Thanks for your work again.

**Comment by Kluzzio** [comment]
@EigentlicherVogel We're going to try to take a look at and fix the other issues (Edit: you brought up) before pushing to CurseForge but yea. The current state was meant to be in the last push but a miscommunication forgoed it. And thank you for your testing once again
