### ISSUE TITLE
Bow Innate Enchantment and Additional Enchantment Not Stacking Properly

### ISSUE THREAD

**Issue by EigentlicherVogel** [chronosacaria/MCDungeonsWeapons#104]
- Versions:
Minecraft 1.18.2
Fabric 0.13.3
MCDW 4.2.5

- Other mods:
Mmm...mM(Training Dummy Mod) 1.5.1
Sodium 0.4.1+build15

- Description:
Bows with Innate enchantments can be further enchanted with either the table or the anvil, including being enchanted with the same enchantment as the Innate one, but at higher levels. If the stacking of identical enchantments happen, then the bow will use the level of the innate enchantment regardless of the added level(s).

-Reproduction
1. Obtain Master's Bow or Elite Power Bow
2. Use Anvil to enchant bow with Power V
3. Spawn in normal spiders (16 health) and shoot them with the enchanted bow
4. The spiders could not be reliably one-shot despite a vanilla bow with Power V being able to do so
Alternatively, with any damage number mods, the damage difference could be numerically confirmed.

**Comment by Kluzzio** [comment]
This issue ~~seems to be~~ is with enchant giver as a whole ~~, although we may be missing something~~. This issue is not exclusive to bow enchantments nor is it exclusive to vanilla enchantments. ~~It is entirely possible that this has become an issue in 1.18.2 due to the seemingly endless tag issues.~~ Thank you for your vigilance in finding this! We will work to find a solution but it is entirely possible that there will not be one for some time. In the meantime, please default to turning off the innate enchantments via the enchant giver config so that this bug does not nerf your experience.

Edit (as I'm writing this): Apparently this was an issue in previous versions and is not due to 1.18.2

Additional Edit: A potential solution has been found and may be implemented at some point but that remains to be seen for now. I will continue to update this thread as new findings are made.

**Comment by Kluzzio** [comment]
Fix submitted for PR: https://github.com/LordDeatHunter/EnchantGiver/pull/6
in this commit: https://github.com/LordDeatHunter/EnchantGiver/pull/6/commits/149ce8019bcaac5dafd0dc9160cceb47486d10c7
Time for pray

**Comment by Kluzzio** [comment]
The old system was abandoned and the switch was mostly made. There are some things that need to be taken care of regarding the maven so that it can work with the mod before this issue is fully resolved. It should only be a matter of time. Once that is done, this issue will be closed and an updated version will be pushed to CurseForge.

**Comment by Kluzzio** [comment]
About ready to go to curseforge. Soon...
