### ISSUE TITLE
Refreshment doesn't seem to do anything

### ISSUE THREAD

**Issue by Mophise** [chronosacaria/MCDungeonsWeapons#107]
I've been running around with Refreshment on my sword and empty bottles in my in inventory for a long time now, and still haven't gotten any health potions out of it. Currently playing the "Another Quality Modpack 2"

**Comment by Kluzzio** [comment]
I believe that refreshment requires you to have bottles in stacks of one and in order for refreshment to trigger, you must kill the enemy. Can you confirm whether this knowledge lets it proc for you? Thanks! In the future it is entirely possible that we may make it so that the bottles do not have to be in stacks of one.

**Comment by Kluzzio** [comment]
Made so that stacked bottles work if there is sufficient space.
