### ISSUE TITLE
All Grave Banes Seem to have disappeared after newest update?

### ISSUE THREAD

**Issue by HacoKavanah** [chronosacaria/MCDungeonsWeapons#113]
Literally nothing else to add.

**Comment by chronosacaria** [comment]
There is a warning on the mod jar, the updates section of the mod page and in Discord stating that because of the new system that you will lose your weapons and to make sure you back up before updating. We did everything to avoid this, but we couldn't prevent it with the new system. That is also why the update is 4.3.0 and not 4.2.6 as the latter would be completely compatible whereas 4.3.0 is not. 

Again, we understand the frustration, but there are warnings in place. As such, this issue will be closed
