### ISSUE TITLE
Dipping Poison Enchantment Broken

### ISSUE THREAD

**Issue by notdynae** [chronosacaria/MCDungeonsWeapons#127]
Dipping Poison III enchantment is broken, does not function

1. Add dipping poison III to bow
2. hold bow in offhand
3. drink health potion

8 poison arrows added to inventory

**Please complete the following information:**
 - Windows
 - Default
 - Mod Version [e.g. 4.4.0]
 - Yes / No [broken in aqmp2 and outside of modpack]

**Comment by chronosacaria** [comment]
See https://github.com/chronosacaria/MCDungeonsWeapons/commit/f258db22461273d70c215fc9c8a026bd04003cd9 for code context.

Dipping Poison does work, but I just realised how awkward it is to use. You need to have the bow with the enchantment in your main hand and the potion in your offhand and drink the potion, which means that there needs to be no arrows in your inventory, otherwise the bow will try to fire rather than the player trying to drink the potion.

**Comment by chronosacaria** [comment]
Changed Dipping Poison to function by holding bow in offhand and drinking potion with main hand to allow for it to work with arrows in inventory (https://github.com/chronosacaria/MCDungeonsWeapons/commit/4b977d2578fcadfc851ca9d3c485befe2968d43e)
