### ISSUE TITLE
Can you make it so that all the enchantments can apply to all of the weapons?

### ISSUE THREAD

**Issue by AzureMonument** [chronosacaria/MCDungeonsWeapons#14]
I'm assuming this is due to the same reason as stated in the reply to my previous bug report (stripping logs) and that it's simply due to the spear being an axe derivative- but the spear (fortune spear this time) is unable to get enchantments such as radiance, shockwave, sweeping edge (which kinda makes sense), poison cloud, and I'm assuming others (this is even with the config 'allow OP enchants' set to true).

Also, don't know if the green enchant just isn't updating or it simply can't have looting III applied.

**Comment by chronosacaria** [comment]
You are correct that because the spears are based on axes that they cannot have a lot of enchants. This is by design as some of them have really powerful innate enchants. 

The other kind of mixing of enchants with the fortune spear, however, that is a problem and should not be happening. I'll take a look at that today.

The green enchant doesn't update, unfortunately. Not yet, anyway. It is what the item will _always_ have even if all of the enchants are stripped from the item. However, you can put Looting III on the fortune spear, for example, it should just list both enchantments as the weaker enchant will be disabled if there is a higher level version applied.

Thanks for brining these issues to my attention, though! :)

**Comment by chronosacaria** [comment]
So, after poking around, it looks like the limitations that you mentioned are limitations of the spears being an AxeItem. I didn't realise how restrictive Axes were with respect to enchantments. I am working on creating a custom item type for the spears. Hopefully that will resolve the issue.

**Comment by chronosacaria** [comment]
This appears to be a limitation based upon Minecraft's code. At this point, the enchants are not able to be applied to axes and AxeItems in the same way that they can be applied to sword and SwordItems. For now, this issue will be converted to a feature request as this is less of an issue with the mod and more of a limit with the base game.

**Comment by chronosacaria** [comment]
This is now possible using the Enchant Giver Config. Any enchantment can be placed on to any weapon
