### ISSUE TITLE
Oversized Shields

### ISSUE THREAD

**Issue by CountSjorn52** [chronosacaria/MCDungeonsWeapons#150]
**Describe the bug**
When the royal guard shield or vanguard shield is holstered by using backslot addon they're significantly larger then they should be
Making it look kinda ridiculous almost as if they're greatshields but they're not.

**Screenshots**

![2022-08-29_08 53 06](https://user-images.githubusercontent.com/93433681/187207654-cd97c9ff-2600-42d5-92d4-473a78d15989.png)
![2022-08-29_08 53 14](https://user-images.githubusercontent.com/93433681/187207657-62d46e08-212d-4361-b44c-f8da339963d7.png)

 - Mod Version 5.0.0.

 - Are you using a Modpack? [e.g. Yes, No; if Yes, which one]

**Additional context**
They just need to be scaled back down to normal size is all.

**Comment by chronosacaria** [comment]
Oh dear lol, yeah that's a bit big

**Comment by chronosacaria** [comment]
Fixed with the following commits:
1.19.x
https://github.com/chronosacaria/MCDungeonsWeapons/commit/f4e140c26b0581429888bd39c5784fe6ba5f2f3a
https://github.com/chronosacaria/MCDungeonsWeapons/commit/03f7a5c152f3aa8204aee636668ef4cbba009a9f

1.18.x
https://github.com/chronosacaria/MCDungeonsWeapons/commit/d4114808aa60faad2fd480e943cd65a2654708e8
