### ISSUE TITLE
Adding a preexisting enchantment on a weapon

### ISSUE THREAD

**Issue by Choo-Choo-Oreo** [chronosacaria/MCDungeonsWeapons#159]
**Describe the bug**
Adding a preexisting enchantment on a weapon (Might be the modpack I'm running)

**To Reproduce Error**
Go to an anvil and combine already existing enchantments on the weapon (I tested it on "Swift Striker, Dark Katana, and the Resolute Tempest Knife"
![image](https://user-images.githubusercontent.com/34584301/189253403-5d04de4b-91e4-4339-9eae-3dcbbdd86af0.png)
**Expected behavior**
An improvement of the already existing "enchantment" on the weapon for it to become more effective.

 - OS: Windows
 - Launcher: Default
 - Mod Version: mcdar-1.5.1-1.18
 - Mod Version: mcda-2.0.7
 - Mod Version: mcdw-5.0.3-1.18
  - Modpack: Yes (Private)
  
  [crash-2022-09-08_22.35.48-client.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/9531880/crash-2022-09-08_22.35.48-client.txt)

**Comment by Kluzzio** [comment]
What is your issue here? I can combine dark katana and smiting 3 just fine. 
![image](https://user-images.githubusercontent.com/96443090/189260398-8d90b02b-6a1a-4a46-806a-c55a2ad5b6ad.png)

If you are crashing when you are trying to put the book in? If so, that's because you need to delete your configs and let them regenerate. Please refer to the announcements made on the discord and the crashlog. If you still experience issues, hop in the discord so we can troubleshoot for you.

**Comment by Choo-Choo-Oreo** [comment]
Yes, it fixes it, thank you for the information.
