### ISSUE TITLE
Soul Devourer enchant doesnt work

### ISSUE THREAD

**Issue by Metalteuffel** [chronosacaria/MCDungeonsWeapons#175]
I've tried all 3 levels of the enchantment, it doesn't add or multiply xp from killing mobs, still only get 3 or 7 exp per kill no matter what mob is killed using the enchantment.

**Comment by chronosacaria** [comment]
@Metalteuffel You're either using an outdated version of the mod or something is wrong on your end. Please fill out the issue report properly, with the appropriate information as found [here](https://github.com/chronosacaria/MCDungeonsWeapons/issues/new/choose). Otherwise we cannot help you.

As the issue report was filled out incorrectly and lacks the necessary information to pursue a solution, it shall be closed.
