### ISSUE TITLE
[Bug Report]: Incompatibility with Impaled-Atlan

### ISSUE THREAD

**Issue by pontorka** [chronosacaria/MCDungeonsWeapons#225]
### Describe the bug; What happened?

I was testing stuff out and I realized that the Atlan from Impaled doesn't accept MCDW enchants.

The Atlan is supposed to be a trident that accepts sword enchantments as well, and it does accept vanilla enchantments

### Expected Behavior

Tried to put Thundering III to non-enchanted Atlan in an anvil, did not work
Tried to put Thundering III to non-enchanted Atlan with /enchant command, did not work

Atlan accepts vanilla sword enchantments, like sweeping edge (pointless, but still is enchantable) and sharpness, hence MCDW sword enchants should be available as well.

### Mod Version

mcdw-5.0.12-1.19

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

Custom

**Comment by chronosacaria** [comment]
@pontorka Could you post a link to the mod that the weapon is from, please? I think I know what is going on, but I'd need to check their code to be sure

**Comment by pontorka** [comment]
> @pontorka Could you post a link to the mod that the weapon is from, please? I think I know what is going on, but I'd need to check their code to be sure

https://www.curseforge.com/minecraft/mc-mods/impaled

**Comment by chronosacaria** [comment]
@pontorka Okay, after taking a look, it appears that the issues is that the Atlan is still, technically, a `TridentItem` which is not supported by any of our enchantments. We, explicitly, remove any `TridentItem` from being able to receive any of our enchantments.

What the author of the mod in question is actually doing is bypassing the type requirement that is set during registration. However, since we've made our enchants to specifically not work with Tridents, their override doesn't affect our enchantments.

Whilst this is unfortunate for your situation, it is the intended functionality. Therefore, we won't be changing the enchantments to accept the Atlan. Sorry
