### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Rogenar** [chronosacaria/MCDungeonsWeapons#228]
### Describe the bug; What happened?

the game crashes before it starts

### Expected Behavior

finding and correcting incompatibility

### Mod Version

8.0.0

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Modpack

1.20.1 0.14.21 fabric

### Additional context

[latest.log](https://github.com/chronosacaria/MCDungeonsWeapons/files/11894025/latest.log)

**Comment by chronosacaria** [comment]
@Rogenar I'll touch base with Apace and see what's going on. When I was testing, I didn't find conflict with Reach Entity Attributes, but I must have missed something. I looks like it is conflicting with Origins because of their use of REA. Shouldn't be too hard to fix though. Thanks for this report
