### ISSUE TITLE
[Bug Report]: mixin crash

### ISSUE THREAD

**Issue by VaporeonScripts** [chronosacaria/MCDungeonsWeapons#308]
### Describe the bug; What happened?

https://mclo.gs/3wfcJAo

### Expected Behavior

normal load

### Mod Version

latest

### Minecraft Launcher

Other

### Operating System

Linux

### Modpack

private

### Additional context

no

**Comment by chronosacaria** [comment]
@VaporeonScripts 
This is not a mixin bug, technically (as the Sinytra Connector requires certain mods to work properly in this context). It is user error. The reason is that you are missing several of the required mods which are noted on both the CurseForge and Modrinth pages.

As stated on the CurseForge page:
Q. Forge?

A. 

When using MCDX on Forge, it is important to make sure that you have the following mods:
So, anything marked with a 🟢 is required. Anything marked with a 🟡 is optional

🟢Sinytra Connector:
https://www.curseforge.com/minecraft/mc-mods/sinytra-connector/

🟢Connector Extras:
https://www.curseforge.com/minecraft/mc-mods/connector-extras/
🟢Forgified Fabric API (in place of the Fabric API):
https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api/

🟢Cloth Config API (Forge Version*):
https://www.curseforge.com/minecraft/mc-mods/cloth-config/
If you are using a version of the Sinytra Connector before 40, use the Fabric version

🟡Clumps (Fabric Version), if you're using Clumps:
https://www.curseforge.com/minecraft/mc-mods/clumps/

As stated on the Modrinth Page:
Q. Forge?
A. MC Dungeons Weapons is compatible with Forge by using the following mods: [Sinytra Connector](https://modrinth.com/mod/connector), [Connector Extras](https://modrinth.com/mod/connector-extras) and the [Forgified Fabric API](https://modrinth.com/mod/forgified-fabric-api) which are being developed by Su5eD. Please make sure to follow all of their instructions in order to have the best experience. If you wish to use [Clumps](https://modrinth.com/mod/clumps), please make sure to use the Fabric version as we rely on a method that is not present in the Forge version.

Please make these corrections, _especially_ changing your Forge Clumps installation to the Fabric version of Clumps and any issues related to MCDX in this situation should be resolved

**Comment by VaporeonScripts** [comment]
Mb,I'll add connector extras ig

**Comment by chronosacaria** [comment]
No worries. Please read through and make sure you make _all_ the necessary changes or you will still crash

**Comment by VaporeonScripts** [comment]
Ye,I love ur mods,ty for being so fast

**Comment by chronosacaria** [comment]
@VaporeonScripts Thank you for your kind words! I'm so glad you're enjoying them. Btw, if you run into issues, it is much faster to get a hold of us on Discord. You can find it here: https://discord.gg/7RCRy2CuyC
