### ISSUE TITLE
mcdw-1.9.1-1.16.4 stunning crash

### ISSUE THREAD

**Issue by superon** [chronosacaria/MCDungeonsWeapons#4]
don't know if i should be posting this as it marked as beta and i think you maybe know about this already..
today i've been going through the enchants to get a feel for what they do, half i can work out, half i can't and the other one simply crashes the server:
https://pastebin.com/R7GiWWhb

**Comment by chronosacaria** [comment]
Thank you so much for taking a whack at the Beta. You absolutely can post issues that you find in the Beta here. I appreciate you mentioning this issue and posting the crash. This issue should be fixed in the release, but I won't mark it as closed until I am sure.

I'm also considering adding lore to the books which should help make sense of them.

**Comment by chronosacaria** [comment]
@superon Would you mind trying the latest release to see if the crash you were experiencing is gone? You'll have to download it from GitHub since CurseForge is in read only mode for the time being.

[Latest Release: 2.0.0-1.16.4](https://github.com/chronosacaria/MCDungeonsWeapons/releases/tag/2.0.0-1.16.4)

**Comment by superon** [comment]
maybe something specific to my server?  works fine in single player but i guess you know that already..
https://pastebin.com/KvWAfzP6 :/

**Comment by chronosacaria** [comment]
That is so strange. Let me try to run it on my server. I'll let you know what happens.

**Comment by chronosacaria** [comment]
Nope, it isn't just you. Were there any other enchants that caused a crash like this?

**Comment by superon** [comment]
initially just this one, i've not retested the others though i imagine they're untouched and still fine

**Comment by superon** [comment]
i didn't test them super hard to be fair, maybe others have this problem given certain conditions..  i imagine the freezing one would be similar but freezing and stunning would be applicable to bow and swords but not both.    on that note i had seen the enchants applicable to bow could be placed on swords and enchants for swords could be placed on bows.

**Comment by chronosacaria** [comment]
I found the problem and it was a big oof on my part. I'm fixing it now. 

I'll take a look at the exclusivity. I thought I took care of that, but maybe I missed something or forgot.

Thank you, so much, for all of this. It really helps a lot.

**Comment by superon** [comment]
\o/
the exclusivity issue was on the previous beta so may well have been resolved 👍 
on that subject i wonder how plausible it would be to introduce a config where server owners can choose to have the enchants apply only to particular weapons (jungles poison only on the green menace for example)? only just seen this enchant added with a few others

**Comment by chronosacaria** [comment]
That's possible, I think? lol
I am still learning configs, so there are some settings about combinations and whatnot. I can look into it for a later release though! :D

**Comment by chronosacaria** [comment]
Okay, should be fixed. The exclusivity thing, though; I have a feeling that is going to take some time. There don't appear to be any crashes from it, but it does strike me as kind of funny that you could enchant a bow with a melee enchantment, run up and bean something and the enchant take effect :P

Since I tested it and the crash is gone, I am going to close this issue.

Thanks again! :D
