### ISSUE TITLE
Levitation effect from bows not ending

### ISSUE THREAD

**Issue by Flyvee** [chronosacaria/MCDungeonsWeapons#64]
On our server we have the MC Dungeons Weapons and Armours mods, and from the weapons mod, the levitation effect that can be applied through the use of the dark enchanter mod, causes those struck by the arrows to levitate, the problem is that the levitation effect doesn't stop when the timer reaches 0. Clearing effects doesn't remove the levitation effect either. So far we have found the only way to stop it, is if the player relogs. I realize that it is possible that this enchantment is still in testing which is why it doesn't appear naturally on any of the bows, but this is mostly to help you in fixing the levitation enchantment.

**Comment by chronosacaria** [comment]
I appreciate the feedback so much as you can imagine, testing against so many other mods is virtually impossible. 

Could you provide a server log so that I can see what version of the mods you're using or just provide a list? I only as that you either do the log or type it out as I sometimes use a screen reader as I am visually impaired and I will have difficulty if you post it as an image. 

Thank you again!

**Comment by Flyvee** [comment]
I checked the closed issues and it seems that because we use the toggleable pvp mod, the effect only happens between players that have the pvp off so I guess it is an issue on that mod's side.

**Comment by chronosacaria** [comment]
Ah, okay, yeah. That makes sense. I've not really been able to figure out a way around getting my mod to work with that mod. They may need to add the compatibility on their end, but once I get my computer up and running again, I'm gonna be looking into this more deeply

**Comment by chronosacaria** [comment]
As there is not much that I can do on my end with respect to this custom pvp mod, I am closing this issue.
