### ISSUE TITLE
Prospector not working

### ISSUE THREAD

**Issue by sororbadr** [chronosacaria/MCDungeonsWeapons#86]
I have a diamond sword with prospector 1 and i've killed hundreds of mobs with no emeralds dropping

**Comment by chronosacaria** [comment]
What mobs are you killing? What version are you on? Are you using a modpack? Are you on a server or in single player? There is a lot more information that I need.

**Comment by sororbadr** [comment]
> What mobs are you killing? What version are you on? Are you using a modpack? Are you on a server or in single player? There is a lot more information that I need.

I'm playing on 1.18.1 in a self made modpack consisting of 90 mods from aqm 2. I've tried killing Zombie piglins, cows, zombies, skeletons, creepers, spiders etc to no avail.

**Comment by sororbadr** [comment]
(on a singleplayer world)

**Comment by Kluzzio** [comment]
With prospector 1, you only have a 5% chance to get the emerald. In addition, it has to be a monster entity that you kill, that means no cows among other harmless entities. If it is indeed not working on your end, it is likely due to one of the mods from aqm 2 (probably Deep Mob Learning: Refabricated), as that modpack loves to cause issues with the MCDX mods.

**Comment by sororbadr** [comment]
I haven't added deep mob learning to my personalized modpack. do Zombie piglins count as harmless mobs?
