### ISSUE TITLE
Incompatibility of Soul Devourer enchantment with Clumps mod

### ISSUE THREAD

**Issue by RedWideWeb** [chronosacaria/MCDungeonsWeapons#87]
The minecraft dungeons wiki doesn't have such thing. I didn't get more XP from an orb as it is stated in your mod's wiki.

Sorry to open an issue but I am confused

**Comment by Kluzzio** [comment]
Extra xp is granted from experience orbs
this.amount = (this.amount * (1 + (soulDevourerLevel / 3)) + Math.round(((soulDevourerLevel % 3)/3.0f) * this.amount));

devourer is guaranteed and can be up to a 3x multiplier 
soul devourer requires you to have the enchanted weapon equipped in mainhand, or (and it stacks) a dual weilding enchanted weapon in offhand

Please ensure that you are using the latest version as well, seeing as how the enchantment is potentially bugged on 4.0.0

**Comment by RedWideWeb** [comment]
@Kluzzio I am using 4.0.3. I don’t get the slightest more xp. Can you please check that or show an exmaple?

**Comment by chronosacaria** [comment]
> @Kluzzio I am using 4.0.3. I don’t get the slightest more xp. Can you please check that or show an exmaple?

Hi @RedWideWeb! Soul Devourer does, indeed, work in all the scenarios that we tested it in (Client, Server, Dev Environment, etc.). If you are only gaining 1 XP at a time (killing slimes, for example) and you only have Soul Devourer I, you will not gain any extra XP, but any other time you will see an increase in your XP gain. Please let me know what weapon you have it on, if you are using it in your offhand or main hand, and if you are on a server or not.

**Comment by Kluzzio** [comment]
Due to lack of response, this issue is being closed.

**Comment by RedWideWeb** [comment]
I was testing. I have many mods and I was trying to figure out which one was causing problems. Turns out it's Clumps. You should know this mod. It optimizes experience orbs. Apparently replacing the xp entity and mcdw cannot apply Soul Devourer. Could you make an addition to your mod so that it works with Clumps orbs?

**Comment by chronosacaria** [comment]
I was kind of concerned that Clumps might cause an issue. We'll definitely take a look at this

**Comment by RedWideWeb** [comment]
@chronosacaria Thank you!

**Comment by chronosacaria** [comment]
Hey, @RedWideWeb! Some bad news for now: It looks like we really can't do a whole lot right now because Clumps isn't applying XP correctly to the player. We have cleaned up the mistakes on our end, but the author of Clumps would have to change the way that they are giving the XP to the player before much could really be done.

The commit that Kluzzio made does, indeed, make the experience apply properly, without killing the XP orbs like was happening before.

As such, we are going to have to close this issue for now. If you happen to open up an issue with the author of Clumps and they reach out, we can reopen it.

**Comment by RedWideWeb** [comment]
Thank you very much! I will try to reach out Clumps dev
