### ISSUE TITLE
Some enchantments do not work as intended.

### ISSUE THREAD

**Issue by ZeburaBlack** [chronosacaria/MCDungeonsWeapons#90]
|Version|
Minecraft 1.18.1
fabric-loader-0.12.12-1.18.1

ModList:
**MmmMmmMmmMmm**(1.5.0)
**MC Dungeons Armors**(1.9.0)
**MC Dungeons Weapons**(1.4.3)
**MC Dungeons Artifacts**(4.0.2)
**Enchantment Description**(9.0.11)
**Sodium**(0.4.0-aplha6+build.14)
**Mod Menu**(3.0.1)
**ToroHealth Damage Indicators**(1.18-fabric-2)

Descriptions from "[Wiki](https://github.com/chronosacaria/MCDungeonsWeapons/wiki)"

Tested on Dummy and Mobs.

- Void Shot (BOW/CROSSBOW) "Deal multiplicative damage based on enchantment level" | Upon triggering, teleport sound is applied like Void Strike but no additional damage is applied.
- Growing (BOW/CROSSBOW) "Deal extra damage the farther you are from the target" | Doesn't do what description says, damage consistent at all ranges.
- Chains (SWORD/AXE) "Pull Enemies together and slow them down" | When triggered instead of pulling together and slowing it seems to remove all other mobs caught by the slow, other than initial enemy. Upon further testing, it seems to just LAUNCH the other enemies through the ground or into orbit.

**Comment by Kluzzio** [comment]
Thanks for telling us! Will look into soon and should be fixed in next release!

**Comment by Kluzzio** [comment]
That gravity bug is funny but being fixed. Thank you for finding that, it's hilarious

**Comment by Kluzzio** [comment]
![image](https://user-images.githubusercontent.com/96443090/151677681-c3e843c2-ecbf-4375-88b8-b08f96fb3a41.png)

Okay, Gravity was funny and I'm sad at how long it took me to notice what was wrong here. The tragedy of copy paste I guess.
Super easy fix though. And I know what is wrong with the other two, it's modifying only the damage of the arrow but because of how the calculations are done currently it's actually trying to decrease damage and failing so the result is that it is unchanged. Thank you again, and if you find any other oddities with enchantments do let us know!

**Comment by Kluzzio** [comment]
Current fixes are lazy for Void Shot and Growing. Because of this, this issue should be left open until they are adapted to not cause any issues. A template is in place for how they can be adapted back to mixing into "onEntityHit" but as a modify variable so that nothing is infringed on. Current implementation has a soft bug attached to it, but it is avoidable and all three current implementations have been tested to work. The lazy part is they each just kill the arrow entity after they damage the target so the arrow doesn't bounce back. @chronosacaria will take a look at rebalancing the enchantments if necessary on Monday as well.

**Comment by Kluzzio** [comment]
Oh yea, those 2 are also lazy because I changed the damage source to Generic from Arrow to avoid a loop but this should be solved with a modify variable.

**Comment by Kluzzio** [comment]
Modify Variable changes were made and they work, so this issue will be closed.
